### ISSUE TITLE
pixi.flump on github not on haxelib

### ISSUE THREAD

**Issue by gludion** [jackwlee01/pixi-flump-runtime#12]
hello,
when downloading pixi-flump-runtime using haxelib `haxelib install pixi-flump-runtime`
the package pixi.flump - which seems necessary - is missing.
Is this a different version?

**Comment by gludion** [comment]
mh.. I'm probably wrong: tried to run the Monster example using Main.hx copied from github, but importing haxelib library.

**Comment by jackwlee01** [comment]
Apologies, I may have updated a version on haxelib with broken examples. I
will be putting up a new version of the library in the next couple of days
with fixed examples :)
