### ISSUE TITLE
display issues with transformed symbols (with links to illustrate)

### ISSUE THREAD

**Issue by NicolasVereenoghe** [jackwlee01/pixi-flump-runtime#14]
Hello,

I use a MovieClip symbol which contains several Sprite symbols. I apply a cocktail of scale + rotation + skew on them, and try to understand when problems occure.

It seems that rotation + skew only works on symbols which have homogen scale (same scale.x and scale.y). You can also apply skew and non homogen scale on symbols which have a rotation of 0° or 180°.

Other cases seems to fail.

Demo project (built with Haxe, pixi v3, updated libraries included into project folder haxe/lib/) :
https://github.com/NicolasVereenoghe/git.vega.pixi3.testFlump

Running demo :
http://a-lyrae.com/demo/flump/

Screenshot of the original Flash scene :
https://github.com/NicolasVereenoghe/git.vega.pixi3.testFlump/blob/master/tmp/shot.jpg

The original Flash source :
https://github.com/NicolasVereenoghe/git.vega.pixi3.testFlump/blob/master/assets/assetsGame.fla

A friend tested the same Flump exported files, with Flambe, and the display is accurate.

**Comment by NicolasVereenoghe** [comment]
It might not be easy to see the issues through my "quickly deploy mini game" template, so I've just tested the same thing directly drawing on stage, and same problems :

var lMovie : Movie = cast stage.addChild( new Movie( "template"));  
lMovie.x = lMovie.width / 2;
lMovie.y = lMovie.height / 2;

**Comment by NicolasVereenoghe** [comment]
There might be a kind of patch to correct this transformation issue.

1) Apply scale to the layer child, not the layer itself :
Into pixi.flump.Movie::renderFrame, at line 317 and 318 :
layer.scale.x = scaleX;
layer.scale.y = scaleY;
Instead :
if ( layer.children.length > 0){
    layer.getChildAt( 0).scale.x = scaleX;
    layer.getChildAt( 0).scale.y = scaleY;
}else trace( "WARNING : Movie::renderFrame : " + symbol.name + " : " + layer.name + " : empty");

2) Apply the renderFrame on a Movie after its children are added
Into flump.MoviePlayer::render, from line 317 to 327 :
movie.renderFrame(
    keyframe,
    (keyframe.location.x + (next.location.x - keyframe.location.x) \* interped),
    (keyframe.location.y + (next.location.y - keyframe.location.y) \* interped),
    (keyframe.scale.x + (next.scale.x - keyframe.scale.x) \* interped),
    (keyframe.scale.y + (next.scale.y - keyframe.scale.y) \* interped),
    keyframe.skew.x + (next.skew.x - keyframe.skew.x) \* interped,
    keyframe.skew.y + (next.skew.y - keyframe.skew.y) \* interped,
    keyframe.alpha + (next.alpha - keyframe.alpha) \* interped,
    lColor
);
Move this right after line 346, so that the content of the movie instance would be scaled.

I call this a patch because I'm not sure if I break something.

A big problem is that you can no longer modify the scale property of a layer's child into your code because it is refreshed at render time to its orginal.

As far as I understand, when you use the skew property of a pixi Container, if you also modify the scale, the scale transformation is applied on a not skewed landmark. On the contrary, when you use the rotation property, if you also modify the scale, the scale is applied on a rotated landmark.
myContainer.skew( myRotation, myRotation)
is not equivalent to
myContainer.rotation = myRotation
as stated in pixi.flump.Movie::renderFrame

I hope it makes sense, I'll try to use this patch ...

**Comment by mathieuanthoine** [comment]
Nico , maybe you can submit a PR ;)

**Comment by NicolasVereenoghe** [comment]
Hey :)

It implies that you can no longer modify scale property of a layer's child, which is very annoying :)
on the other hand, the display is accurate :)

Maybe, there is a better solution ? I would access a transform matrix but it doesn't seem to be available on local landmark ... though, there's a worldTransform property, but it doesn't seem to help ?

**Comment by gludion** [comment]
hi Nicolas,
the cause of this bug seems deeply rooted in pixi's way to handle transforms, as explained here:
https://github.com/pixijs/pixi.js/issues/3163
Meanwhile, probably your idea to put the scale in a child is the simplest fix. 

(One thing to test would be to check that toLocal() and toGlobal() still work correctly from flump Movies inside a flump Movie etc.)

**Comment by NicolasVereenoghe** [comment]
Hello :) I've just sent a pull request to propose the fix. I'll test this, thanks :)

**Comment by jackwlee01** [comment]
Thanks for looking into this issue. Happy to incorporate the pull request.

For now I will leave this issue open just incase there are some unforeseen side effects.

**Comment by NicolasVereenoghe** [comment]
@gludion toLocal() and toGlobal() seem to still work correctly

**Comment by NicolasVereenoghe** [comment]
Hey, i've just built another fix.

In order to solve the transform issues, due to the difference between flash or flump on one hand, and pixi on the other hand. They interpret the scale and the skew transformations not in the same order :s

With 0.2 pixi-flump :
http://a-lyrae.com/demo/flump0.2/

With my fix, flash and html look the same :
http://a-lyrae.com/demo/flump0.2fix/

Like previously, the scale is shift from the layer to the children, but this time I also apply the x & y offsets to the child ;)

**Comment by NicolasVereenoghe** [comment]
the code for my test :
https://github.com/NicolasVereenoghe/git.vega.pixi3.flump

the flash source animation :
https://github.com/NicolasVereenoghe/git.vega.pixi3.flump/blob/master/assets/assetsTest.fla

**Comment by NicolasVereenoghe** [comment]
PR sent ... canceled, need more tests

**Comment by NicolasVereenoghe** [comment]
Hello :)

Finally, I think I have something good !
before : http://a-lyrae.com/demo/flump0.2/
aflter : http://a-lyrae.com/demo/flump0.2fix/

A part of the Movie::renderFrame had to be rewritten. It now manages much more things !

I had to understand that parameters received by the renderFrame function had to be interpreted differently if we treat a flipbook (weird), a Movie or a Sprite.

As previously, the scale needs to be applied to the layer's child to conform to flash/flump model. It manage offset between transform point and origin that you can use in flash.

Updated flash source animation :
https://github.com/NicolasVereenoghe/git.vega.pixi3.flump/blob/master/assets/assetsTest.fla

I did a lot of testing, I hope it doesn't break anything because this fix brings new oportunities ;)
