### ISSUE TITLE
getting build errors

### ISSUE THREAD

**Issue by yordan-kanchelov** [jackwlee01/pixi-flump-runtime#24]
Hey guys I am new  to haxe and I have some struggle to  build it to js using your build.hxml . 

I get these errors when I try to use it. Could you give me some help ? 
```
./src/flump/filters/AnimateTintFilter.hx:2: characters 7-55 : Type not found : pixi.core.renderers.webgl.filters.AbstractFilter
./src/PixiFlumpMain.hx:4: lines 4-15 : Defined in this class
./src/pixi/flump/Movie.hx:16: lines 16-434 : pixi.flump.Movie is not ready to be accessed, separate your type declarations in several files
./src/pixi/flump/Resource.hx:19: lines 19-115 : Defined in this class
./src/pixi/flump/Movie.hx:16: lines 16-434 : pixi.flump.Movie is not ready to be accessed, separate your type declarations in several files
./src/pixi/flump/Resource.hx:19: lines 19-115 : Defined in this class
./src/pixi/flump/Resource.hx:107: characters 4-19 : pixi.flump.Movie should be pixi.core.display.DisplayObject
```

**Comment by NicolasVereenoghe** [comment]
Hello,

I cannot answer for the build.xml, but the 1st error may be related to the pixi version you're using.

The runtime is written for pixi v3, but you can enable pixi v4 support by modifying these lines :
1)
https://github.com/jackwlee01/pixi-flump-runtime/blob/master/src/flump/filters/AnimateTintFilter.hx#L2-L4
2)
https://github.com/jackwlee01/pixi-flump-runtime/blob/master/src/flump/filters/AnimateTintFilter.hx#L26-L28
3)
https://github.com/jackwlee01/pixi-flump-runtime/blob/master/src/pixi/flump/Movie.hx#L311-L312

I'm still using pixi v4.0.2, I need to upgrade to 4.2.1 and see if evrething is still alright ...

**Comment by NicolasVereenoghe** [comment]
Upgrade done, at first glance it's ok.

If you're new with haxe, you can review my tests. I work with HaxeDevelop on Windows. It is configured to include the libs localy into the project, more easy to start from this ... if it helps ... :
https://github.com/NicolasVereenoghe/git.vega.pixi4.flump

**Comment by yordan-kanchelov** [comment]
@NicolasVereenoghe Thanks mate! I will try everything tomorrow. Cheers
