### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by adireddy** [jackwlee01/pixi-flump-runtime#4]
Hey @jackwlee01, firstly this is not an issue.

Great work with the library :+1: 

I have never used flump before and after spending a few hours playing with it this morning I think it's really good.

@mathieuanthoine told me about flump many times but I never had a chance to look into it.

I have a few questions:
- I am thinking of integrating this with pixi-haxe and would like to know your thoughts about it.
- As this is a pure haxe library, I want to make it available for JS users as well as a plugin like Spine.
- Are you planning to make it available on any other libraries apart from pixi?
- Please let me know if you are interested in making this a part of pixi-haxe project under pixi.js organisation so that I can add you as collaborator and you can continue working in pixi-haxe directly instead of having dependencies.

**Comment by jackwlee01** [comment]
Hey adireddy, glad you like the library!

I have some thoughts about the questions you asked.

I would indeed like to make this available for non-Haxe users as a plugin. I haven't yet made it available as I have been testing it out and getting valuable feedback on the library from mathieuanthoine. The library is pretty solid now, although there are a few more API changes that I am going to make once the skew feature makes its way into the master branch of pixijs.

I have also heavily considered making a flump runtime for other libraries. You will notice that the code has been split into generic code (in the flump package) and library specific code (the pixi package). The pixi code is mostly a relatively simple facade which tweaks the behaviour and API (and also the plugin loading). At some point in the future, when I wish to make a second runtime, I will split the flump package off into its own project to be included as a sub-module.

In terms of integrating this lib into pixi-haxe, it sounds like something I might be interested in. It would certainly give it more visibility. One benefit I see in keeping it separate though is that it can better accommodate non-haxe users, which I imagine would be the majority of people interested in this library. How do you imagine the repo would be set up to accommodate for the non-haxe users?

**Comment by jackwlee01** [comment]
Also, please let me know if you have any feedback on the API and the package naming!

**Comment by adireddy** [comment]
As you are considering making a flump runtime for other libraries which is great, it's ideal for it to be in its own repo.

Coming to pixi, I managed to generate JS library for non haxe pixi users https://github.com/pixijs/pixi-haxe/tree/flump/dist

I copied your library to https://github.com/pixijs/pixi-haxe/tree/flump/pixi/plugins/flump and changed the package structure slightly.

All of this is in a separate branch `flump` for my testing.

JS library is really important for pixi.js users.

My goal is to make it easy for haxe-pixi users and also make it available to JS users. So not really sure yet whether to duplicate your code or not :)

**Comment by jackwlee01** [comment]
Are you able to include the code as a git submodule, or as a haxelib? Duplication won't be very good for maintainability.

I think it would make more sense to keep the javascript distribution in the same repo as the runtime source, so that the project is nicely self-contained. I think putting it into the pixi-haxe repo makes things more confusing for pure javascript users. If the dist stays in the pixi-flump-runtime repo they can log issues and track history much easier than if it were bundled into the pixi-haxe repo.

**Comment by adireddy** [comment]
You are right. Makes sense to keep everything together.
